/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123073-g743df5ded9-20260228"
#endif /* AVUTIL_FFVERSION_H */
